name: Create release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-zip-upload:
    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: 'mappps'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

        # Compile the plugin
      - name: Compile CSS and Javascript
        run: |
          npm ci --ignore-scripts
          npm run build && npm run build:blocks

      # Zip le plugin dans une release clean de tout fichiers inutiles
      - name: Zip release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: '${{ env.RELEASE_NAME }}.zip'
          path: 'mappps.php license.txt lang/ build/ includes/ templates/'

      # Publie la release
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ env.RELEASE_NAME }}.zip'
          generateReleaseNotes: true
